[project]
name = "function-calling-tutorial"
version = "0.1.0"
description = "A tutorial on function calling using Gemma 3 via Ollama."
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
    "rich>=14.0.0",
]
